### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Smeat** [Smeat/dobson-star-tracker#1]
- [ ] Add interface for getting gps/time from phone via bluetooth/wifi
- [ ] Connection to Stellarium and KStars via wifi
- [x] Schematic
  -  [X] Find a display with red background light
     - The LEDs on the Nokia 5110 LCD can easily be replaced
  -  [ ] SD support for saving star maps
   - [ ] Implement filesystem or use a faster fat lib
      - Fat reads were at 0.5MB/s. RAW at 7MB/s
         - SIMBAD library for Vmag <11 is about 16mb for the data and 30mb for the names
      - [ ] UI for selecting targets, calibrating etc
- [ ]  Actually get the hardware and test it

**Comment by Smeat** [comment]
Using another project: https://github.com/Smeat/Star_Tracker
